import QtQuick

/* Generated by AI (Copilot: GPT-5.5) */
Item {
    id: root

    property bool running: true
    property color baseColor: "#79c8ff"
    property color highlightColor: "#e7f8ff"
    property color trailColor: "#8bdcff"
    property int baseWidth: 1
    property int highlightWidth: 2
    property int trailWidth: highlightWidth * 2
    property int borderRadius: 6
    property real highlightLength: Math.max(54, Math.min(120, Math.min(width, height) * 0.26))
    property real trailLength: highlightLength * 1.75
    property real phase: 0

    readonly property real perimeter: Math.max(1, 2 * (width + height))
    readonly property real distance: phase * perimeter
    readonly property real topDistance: width
    readonly property real leftDistance: topDistance + height
    readonly property real bottomDistance: leftDistance + width

    function clamp(value, minimum, maximum) {
        return Math.max(minimum, Math.min(maximum, value))
    }

    Rectangle {
        anchors.fill: parent
        color: "transparent"
        border.color: root.baseColor
        border.width: root.baseWidth
        radius: root.borderRadius
        opacity: 0.72
    }

    Item {
        id: topEdge
        readonly property real edgeDistance: root.distance
        readonly property real coreLength: Math.min(root.highlightLength, root.width)
        readonly property real fadeLength: Math.min(root.trailLength, root.width)

        visible: edgeDistance < root.topDistance
        anchors.fill: parent

        Rectangle {
            x: root.clamp(root.width - topEdge.edgeDistance - width / 2, 0, root.width - width)
            y: 0
            width: topEdge.coreLength
            height: root.highlightWidth
            radius: height / 2
            color: root.highlightColor
        }

        Rectangle {
            x: root.clamp(root.width - topEdge.edgeDistance - width / 2, 0, root.width - width)
            y: root.baseWidth + 1
            width: topEdge.fadeLength
            height: root.trailWidth
            radius: height / 2
            opacity: 0.62
            gradient: Gradient {
                orientation: Gradient.Horizontal
                GradientStop { position: 0.0; color: "transparent" }
                GradientStop { position: 0.5; color: root.trailColor }
                GradientStop { position: 1.0; color: "transparent" }
            }
        }
    }

    Item {
        id: leftEdge
        readonly property real edgeDistance: root.distance - root.topDistance
        readonly property real coreLength: Math.min(root.highlightLength, root.height)
        readonly property real fadeLength: Math.min(root.trailLength, root.height)

        visible: root.distance >= root.topDistance && root.distance < root.leftDistance
        anchors.fill: parent

        Rectangle {
            x: 0
            y: root.clamp(leftEdge.edgeDistance - height / 2, 0, root.height - height)
            width: root.highlightWidth
            height: leftEdge.coreLength
            radius: width / 2
            color: root.highlightColor
        }

        Rectangle {
            x: root.baseWidth + 1
            y: root.clamp(leftEdge.edgeDistance - height / 2, 0, root.height - height)
            width: root.trailWidth
            height: leftEdge.fadeLength
            radius: width / 2
            opacity: 0.62
            gradient: Gradient {
                orientation: Gradient.Vertical
                GradientStop { position: 0.0; color: "transparent" }
                GradientStop { position: 0.5; color: root.trailColor }
                GradientStop { position: 1.0; color: "transparent" }
            }
        }
    }

    Item {
        id: bottomEdge
        readonly property real edgeDistance: root.distance - root.leftDistance
        readonly property real coreLength: Math.min(root.highlightLength, root.width)
        readonly property real fadeLength: Math.min(root.trailLength, root.width)

        visible: root.distance >= root.leftDistance && root.distance < root.bottomDistance
        anchors.fill: parent

        Rectangle {
            x: root.clamp(bottomEdge.edgeDistance - width / 2, 0, root.width - width)
            y: root.height - height
            width: bottomEdge.coreLength
            height: root.highlightWidth
            radius: height / 2
            color: root.highlightColor
        }

        Rectangle {
            x: root.clamp(bottomEdge.edgeDistance - width / 2, 0, root.width - width)
            y: root.height - root.baseWidth - root.trailWidth - 1
            width: bottomEdge.fadeLength
            height: root.trailWidth
            radius: height / 2
            opacity: 0.62
            gradient: Gradient {
                orientation: Gradient.Horizontal
                GradientStop { position: 0.0; color: "transparent" }
                GradientStop { position: 0.5; color: root.trailColor }
                GradientStop { position: 1.0; color: "transparent" }
            }
        }
    }

    Item {
        id: rightEdge
        readonly property real edgeDistance: root.distance - root.bottomDistance
        readonly property real coreLength: Math.min(root.highlightLength, root.height)
        readonly property real fadeLength: Math.min(root.trailLength, root.height)

        visible: root.distance >= root.bottomDistance
        anchors.fill: parent

        Rectangle {
            x: root.width - width
            y: root.clamp(root.height - rightEdge.edgeDistance - height / 2, 0, root.height - height)
            width: root.highlightWidth
            height: rightEdge.coreLength
            radius: width / 2
            color: root.highlightColor
        }

        Rectangle {
            x: root.width - root.baseWidth - root.trailWidth - 1
            y: root.clamp(root.height - rightEdge.edgeDistance - height / 2, 0, root.height - height)
            width: root.trailWidth
            height: rightEdge.fadeLength
            radius: width / 2
            opacity: 0.62
            gradient: Gradient {
                orientation: Gradient.Vertical
                GradientStop { position: 0.0; color: "transparent" }
                GradientStop { position: 0.5; color: root.trailColor }
                GradientStop { position: 1.0; color: "transparent" }
            }
        }
    }

    NumberAnimation on phase {
        from: 0
        to: 1
        duration: 2200
        loops: Animation.Infinite
        running: root.running
    }
}
